# html lang
language: ja

# header
site_brand_name: PAWNYABLE

menu:
  Practice: /practice/
  About: /about/

# stylesheets loaded in the <head>
stylesheets:
- /css/style.css

# scripts loaded in the end of the body
scripts:
- /js/frame.js

# favicon
favicon: /favicon.png

date_format: MMM D, YYYY

# profile
profile:
  description: "Pawnyableは、中〜上級者がpwn(Binary Exploitation)を勉強するための資料です。"
  image: /pawnyable.png
  langs:
    "English": /#
    "简体中文": /#
    "한국어": /#
  links:
    "🐤 Linux Userland": /linux-userland/
    "🐺 Linux Kernel": /linux-kernel/
    "🐑 Windows Userland [工事中]": #/windows-user/
    "🐻 Windows Kernel [工事中]": #/windows-kernel/
    "🐼 Browser Exploit [工事中]": #/browser/
    "🐰 VM Escape [工事中]": #/vm-escape/
    "🦝 Android/iOS Exploit [工事中]": #/phone/
    "🐯 and more...? [工事中]": #/misc/

# footer
footer:
  copyright_info:
    enable: false
    author:

  powered_by: # Powered by Hexo & Frame
    enable: false

  other_info:
    enable: true
    content: © 2023 ptr-yudai 🐈

# color mode: default / classic / dark
color_mode: default

# mathjax setting
# note: need to install the hexo plugin for math: https://github.com/hexojs/hexo-math
mathjax_enable: false
